import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from './components/Sidebar';
import { ReactQueryClientProvider } from './components/ReactQueryClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <Sidebar />
          <div className="ml-16 px-4 py-12">{children}</div>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
